apiVersion: batch/v1
kind: Job
spec:
  template:
    spec:
      containers:
        - name: training-container
          image: docker.io/kubeflowkatib/enas-cnn-cifar10-cpu:latest
          command:
            - python3
            - -u
            - RunTrial.py
            - --num_epochs=1
            - "--architecture=\"${trialParameters.neuralNetworkArchitecture}\""
            - "--nn_config=\"${trialParameters.neuralNetworkConfig}\""
      restartPolicy: Never
